/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package domparser;

import com.sun.org.apache.xerces.internal.parsers.DOMParser;
import java.util.ArrayList;
import java.util.List;
import java.util.Properties;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.xml.parsers.DocumentBuilder;
import javax.xml.parsers.DocumentBuilderFactory;
import javax.xml.parsers.ParserConfigurationException;
import javax.xml.transform.OutputKeys;
import javax.xml.transform.Transformer;
import javax.xml.transform.TransformerConfigurationException;
import javax.xml.transform.TransformerException;
import javax.xml.transform.TransformerFactory;
import javax.xml.transform.dom.DOMSource;
import javax.xml.transform.stream.StreamResult;
import org.w3c.dom.Document;
import org.w3c.dom.Element;

/**
 *
 * @author Jurica
 */
public class GlavniFrame extends javax.swing.JFrame {

    /**
     * Creates new form GlavniFrame
     */
    List<Klub> sviKlubovi;
    public GlavniFrame() {
        initComponents();
        sviKlubovi = new ArrayList<>();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtProracun = new javax.swing.JTextField();
        txtGrad = new javax.swing.JTextField();
        txtIme = new javax.swing.JTextField();
        txtPredsjednik = new javax.swing.JTextField();
        btnDodaj = new javax.swing.JButton();
        btnUXML = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Ime");

        jLabel2.setText("Grad");

        jLabel3.setText("Proracun za natjecateljsku sezonu");

        jLabel4.setText("Predsjednik");

        btnDodaj.setText("Dodaj klub");
        btnDodaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDodajActionPerformed(evt);
            }
        });

        btnUXML.setText("u XML");
        btnUXML.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUXMLActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnUXML, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnDodaj, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)
                            .addComponent(txtPredsjednik)
                            .addComponent(txtProracun)
                            .addComponent(txtGrad)
                            .addComponent(txtIme))))
                .addContainerGap(107, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtIme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtGrad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtProracun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtPredsjednik, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnDodaj)
                .addGap(18, 18, 18)
                .addComponent(btnUXML)
                .addContainerGap(73, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDodajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDodajActionPerformed
        if (provjeriUnos()) {
            unesiKlub();
            obrisiPodatke();
        }
        else{
            JOptionPane.showMessageDialog(null, "Unjeli ste krive podatke");
        }
    }//GEN-LAST:event_btnDodajActionPerformed

    private void btnUXMLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUXMLActionPerformed
        try {
            DocumentBuilderFactory DOMFactory = DocumentBuilderFactory.newInstance();
            DocumentBuilder DOMParser = DOMFactory.newDocumentBuilder();
            napraviXml(DOMParser);
        } catch (Exception ex) {
            Logger.getLogger(GlavniFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnUXMLActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GlavniFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GlavniFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GlavniFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GlavniFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GlavniFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDodaj;
    private javax.swing.JButton btnUXML;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField txtGrad;
    private javax.swing.JTextField txtIme;
    private javax.swing.JTextField txtPredsjednik;
    private javax.swing.JTextField txtProracun;
    // End of variables declaration//GEN-END:variables

    private boolean provjeriUnos() {
        if ("".equals(txtGrad.getText()) || "".equals(txtIme.getText()) || "".equals(txtPredsjednik.getText()) || "".equals(txtProracun.getText())) {
            return false;
        }
        
        try {   
            Float.parseFloat(txtProracun.getText());
            return true;
        } catch (Exception e) {
            
            return false;
        }
    }

    private void obrisiPodatke() {
        txtGrad.setText("");
        txtIme.setText("");
        txtPredsjednik.setText("");
        txtProracun.setText("");
    }
    
    private void unesiKlub() throws NumberFormatException {
        Klub k = new Klub();
        k.setGrad(txtGrad.getText());
        k.setIme(txtIme.getText());
        k.setPredsjednik(txtPredsjednik.getText());
        k.setProracun(Float.parseFloat(txtProracun.getText()));
        sviKlubovi.add(k);
    }

    private void napraviXml(DocumentBuilder DOMParser) throws TransformerConfigurationException, TransformerException {
        Document doc = DOMParser.newDocument();
        Element kluboviElement = doc.createElement("Klubovi");
        for (Klub klub : sviKlubovi) {
            Element klubElement = doc.createElement("Klub");
            
            Element imeElement = doc.createElement("Ime");
            imeElement.appendChild(doc.createTextNode(klub.getIme()));
            
            Element gradElement = doc.createElement("Grad");
            gradElement.appendChild(doc.createTextNode(klub.getGrad()));
            
            Element ProracunElement = doc.createElement("Proracun");
            ProracunElement.appendChild(doc.createTextNode(klub.getProracun() + ""));
            
            Element predsjednikElement = doc.createElement("Predsjednik");
            predsjednikElement.appendChild(doc.createTextNode(klub.getPredsjednik()));
            
            klubElement.appendChild(imeElement);
            klubElement.appendChild(gradElement);
            klubElement.appendChild(ProracunElement);
            klubElement.appendChild(predsjednikElement);
            kluboviElement.appendChild(klubElement);
        }
        doc.appendChild(kluboviElement);
        
        TransformerFactory transFactory = TransformerFactory.newInstance();
        Transformer newTransformer = transFactory.newTransformer();
        StreamResult file = new StreamResult("klubovi.xml");
        newTransformer.transform(new DOMSource(doc), file);
    }
}